/*


Filters allow you to limit and modify the data that is included in a view. For example, you can use filters to exclude traffic from particular IP addresses, focus on a specific subdomain or directory, or convert dynamic page URLs into readable text strings. Read more: https://support.google.com/analytics/answer/1033162?hl=en&ref_topic=1032939


========================================================================================================================================
Metrics are quantitative measurements. The metric Sessions is the total number of sessions. The metric Pages/Session is the average number of pages viewed per session.


========================================================================================================================================

You can share Dashboards, Custom Reports, Segments, Goals, and Custom Attribution Models in the Solutions Gallery. Only configuration data is shared through the Solutions Gallery. When you create and share an asset, your personal information and Analytics data stays private in your account. And when you import an asset from the Solutions Gallery, only the template is imported into your account.

Except Custom Dimensions

========================================================================================================================================
A session is a group of interactions that take place on your website within a given time frame. By default, a session lasts until there's 30 minutes of inactivity, but you can adjust this length so a session lasts a few seconds or several hours. A session can be as short as a few seconds or as long as several hours. A single user can open multiple sessions.

========================================================================================================================================
What would you set up to track metrics that don't appear in Google Analytics by default? e.g. how many comments users posted to a webpage on your site.

Custom metrics can produce more flexible and more readable custom reports and as such are a convenient way to track your most important metrics.

========================================================================================================================================
A segment is a subset of your Analytics data. Segments let you isolate and analyze those subsets of data so you can examine and respond to the component trends in your business. You can also use segments as the basis for audiences. A segment is made up of one or more non-destructive filters (filters that do not alter the underlying data). Those filters isolate subsets of users, sessions, and hit.\

========================================================================================================================================

User-level scope allows you to conveniently group all of a user's component sessions and hits by a single value. It is ideal for values that don't change often for a particular use.

========================================================================================================================================

By default, the channel labels that you see in Multi-Channel Funnels reports (Paid Search, Organic Search, Social Network, etc.) are defined as part of the MCF Channel Grouping. If you have specific analysis requirements, you may wish to create your own Custom Channel Grouping(s), each with its own set of labels. When you share a Custom Channel Grouping, only the configuration information is shared. Your data remains private. The following channel labels are defined as part of the MCF Channel Grouping and are the labels used by default in your reports. The channel definitions are not case sensitive.

========================================================================================================================================
Data Import lets you join the data generated by your offline business systems with the online data collected by Analytics. This can help you organize, analyze and act upon this unified data view in ways that are better aligned with your specific and unique business needs. For example, as a web publisher, you could join hits collected by Analytics with data dimensions exported from your CMS and CRM systems to analyze the relative contributions of authors to your site.

========================================================================================================================================

By adding campaign parameters to your URLs, you can identify the campaigns that send traffic to your site. When a user clicks a referral link, these parameters are sent to Analytics, so you can see the effectiveness of each campaign in your reports. Google Adwords gives you an option to track campaign using auto-tagging.

========================================================================================================================================

Acquisition-related metrics answer questions such as: how did people get here, and who are they?

Users → the visitors who initiated at least one session in the date range of interest

New Users → the number of first-time users (as opposed to returning ones) in the date range

Sessions → Google Analytics starts recording a session whenever someone visits a website and terminates it after 30 minutes of inactivity. GA keeps track of all user interactions that take place within that specified time frame.



========================================================================================================================================

Behavior-related metrics answer questions such as: how did people behave once they got here?

Bounce Rate→ the percentage of all single-page sessions where the Analytics server did not record any interactions (e.g. where the visitor landed and left without clicking on any links and navigating to a second page)

Exit Rate (shown as '% Exit') → the number of exits / number of pageviews for the specified page

Pages/Session → the average number of pages viewed within a single session

Session Duration → the average length of a session
========================================================================================================================================
Conversion-related metrics answer questions such as: how many people did convert, and how much revenue did we get?

Ecommerce Conversion Rate → the percentage of sessions that included an ecommerce transaction

Transactions → the number of transactions (i.e. completed purchases) that took place

Revenue → the amount of money generated from the transactions

========================================================================================================================================

The pages through which visitors entered your site are called landing pages.

========================================================================================================================================

Through which report can you determine which browsers may have had problems with your website? - Browser and OS report

========================================================================================================================================

The URL Builder has six fields, but you generally need to use only Campaign Source, Campaign Medium, and Campaign Name

========================================================================================================================================

Through which report can you determine the percent of your site traffic that has visited previously?


New Vs Returning Report 


========================================================================================================================================



========================================================================================================================================



========================================================================================================================================


========================================================================================================================================


========================================================================================================================================

========================================================================================================================================



========================================================================================================================================


========================================================================================================================================


========================================================================================================================================



========================================================================================================================================



========================================================================================================================================


========================================================================================================================================


========================================================================================================================================

========================================================================================================================================



========================================================================================================================================


========================================================================================================================================
*/
